spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Gengsl!@#123
    url: jdbc:mysql://192.168.20.97:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
    hikari:
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
  application:
    name: order
  rabbitmq:
    host: 192.168.20.97
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
env: test5
girl:
  name: lili
  age: 29
